name: money_management_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

#-----------------DEPENDENCIES
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  auto_route: ^9.2.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  gap: ^3.0.1
  injectable: ^2.5.0
  get_it: ^8.0.2
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.2
  flutter_native_splash: ^2.4.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  syncfusion_flutter_charts: ^28.1.35
  # intl: ^0.19.0
  intl: ^0.20.0
  meta: ^1.10.0
  path: ^1.9.0
  fluttertoast: ^8.2.10
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler: ^11.3.1
  flutter_timezone: ^4.0.0
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.1
  internet_connection_checker: ^3.0.1
  table_calendar: ^3.2.0
  flutter_image_compress: ^2.4.0
#-----------------DEPENDENCIES

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner:
  injectable_generator:
  change_app_package_name: ^1.4.0
  json_serializable:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/Onboarding1.png
    - assets/images/onboarding/Onboarding2.png
    - assets/images/onboarding/Onboarding3.png
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
